import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>莫远华的技术分享</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">ijike.wang</a>
        </h1>

        <p className={styles.description}>
          去行动 去记录 去分享
          <code className={styles.code}>hello / world</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>博客 &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>



          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>关于我 &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <div style={{
          color: "#ececec",
          fontSize: '0.9rem'
        }}>
          <a
            href="https://beian.miit.gov.cn/#/Integrated/recordQuery"
            target="_blank"
            rel="noopener noreferrer"
          >
            湘ICP备18001866号-1
          </a>
        </div>

      </footer>
    </div>
  )
}
